### PR TITLE
Support for other models.

### PR DESCRIPTION
**Pull request by YZBPXX**

### CODE REVIEW

**Comment by xiaohu2015** [comment]
can you also add a notebook?

**Comment by YZBPXX** [comment]
> can you also add a notebook (e.g. IP-Adapter SD 1.5)?


sure

**Comment by xiaohu2015** [comment]
hi, I think you delete the file, why?

**Comment by YZBPXX** [comment]
I think I made a mistake and I will check it later



---Original---
From: "Hu ***@***.***&gt;
Date: Thu, Jan 4, 2024 11:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tencent-ailab/IP-Adapter] Support for other models. (PR #223)




 
hi, I think you delete the file, why?

**Pull request merged**
